<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>password</name>
   <tag></tag>
   <elementGuidId>8ac6b8a3-16f9-43d2-a04e-2bb88e290b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;ctl00_CPHContainer_txtPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;ctl00_CPHContainer_txtPassword&quot;]</value>
      <webElementGuid>083500bc-2d37-4f96-9b84-efcc5c27de82</webElementGuid>
   </webElementProperties>
</WebElementEntity>
